In [1]:
### numpy-> Play with arrays
### pandas-> dataset
### matplotlib-> data visualisation
###seaborn-> data visualisation
### scipy-> statistical
### sklearn-> algorithm





In [2]:
import numpy as np
simple_list=[6,7,9]
np.array(sample_list)

NameError: name 'sample_list' is not defined

In [3]:
simple_list=[6,7,9]
np.array(sample_list)

NameError: name 'sample_list' is not defined

In [ ]:
arr=np.array([6,7,9])

In [4]:
np.arrange(5,15)

AttributeError: module 'numpy' has no attribute 'arrange'

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [7]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [9]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [10]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [11]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [16]:
np.random.rand(3,5)

array([[0.94547939, 0.43367515, 0.1505705 , 0.01302078, 0.21963607],
       [0.2991541 , 0.55315824, 0.48417373, 0.29461486, 0.40186203],
       [0.04364956, 0.75985577, 0.96630527, 0.91908435, 0.30440688]])

In [17]:
arr=np.random.rand(2,4)
arr

array([[0.22538497, 0.4569673 , 0.50407634, 0.40103214],
       [0.43332575, 0.73464453, 0.11913538, 0.63209776]])

In [18]:
np.random.randint(2,100)

90

In [19]:
np.random.randint(20,56,100)

array([49, 51, 42, 38, 51, 47, 45, 54, 42, 27, 47, 21, 40, 54, 51, 37, 49,
       46, 50, 23, 38, 35, 55, 35, 27, 39, 20, 35, 53, 41, 21, 47, 31, 24,
       44, 32, 50, 36, 29, 47, 28, 24, 55, 40, 45, 52, 23, 37, 30, 40, 38,
       28, 48, 46, 27, 34, 39, 30, 32, 45, 52, 39, 39, 30, 43, 47, 40, 45,
       38, 27, 21, 45, 32, 48, 37, 55, 33, 53, 51, 48, 48, 50, 45, 36, 25,
       48, 45, 53, 53, 29, 33, 32, 53, 54, 27, 52, 26, 21, 47, 55])

In [20]:
np.random.randint(10,23,99)

array([10, 18, 10, 13, 14, 12, 16, 18, 11, 18, 15, 20, 18, 19, 15, 19, 17,
       18, 20, 16, 11, 10, 12, 10, 20, 16, 22, 16, 18, 15, 10, 18, 16, 18,
       20, 17, 20, 21, 19, 18, 11, 18, 11, 13, 10, 22, 16, 19, 13, 17, 13,
       13, 13, 15, 16, 19, 10, 13, 10, 22, 19, 17, 13, 13, 18, 13, 18, 21,
       17, 16, 14, 21, 13, 19, 20, 13, 12, 21, 15, 10, 12, 11, 13, 18, 14,
       20, 19, 11, 14, 22, 20, 22, 13, 18, 21, 13, 15, 13, 16])

In [21]:
sample_array=np.arrange(30)
sample_array

AttributeError: module 'numpy' has no attribute 'arrange'

In [22]:
rand_array=np.random.randint(0,10,50)
rand_array

array([4, 8, 3, 7, 7, 0, 1, 1, 5, 5, 6, 4, 6, 7, 6, 6, 2, 8, 4, 2, 9, 9,
       4, 5, 0, 9, 3, 6, 6, 3, 2, 7, 3, 7, 4, 6, 5, 2, 1, 7, 2, 7, 4, 5,
       2, 5, 9, 8, 9, 3])

In [24]:
smaple_array.reshape(5,6)

NameError: name 'smaple_array' is not defined

In [25]:
smaple_array.reshape(5,6)

NameError: name 'smaple_array' is not defined

In [26]:
rand_array.max()

9

In [27]:
rand_array.argmax()

20

In [28]:
a=np.eye(5)

In [29]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
a.np.random.rand(2,3)

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [32]:
a.np.random.rand(2,3)

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [34]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
sample_array=np.arrange(10,11)

AttributeError: module 'numpy' has no attribute 'arrange'

In [36]:
sample_array=np.arrange(10,21)

AttributeError: module 'numpy' has no attribute 'arrange'

In [38]:
sample_array=np.arrange(10,21)


sample_array

AttributeError: module 'numpy' has no attribute 'arrange'

In [39]:
sample_aarray[0]

NameError: name 'sample_aarray' is not defined

In [40]:
sample_array[2:5]

NameError: name 'sample_array' is not defined

In [41]:
sample_array=np.arange(10,21)

sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
sample_array(0)

TypeError: 'numpy.ndarray' object is not callable

In [43]:
sample_array[2:5]

array([12, 13, 14])

In [44]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [45]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [47]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [48]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two-Dimensional Array

In [3]:
import numpy as np

In [4]:
sample_matrix=np.array([50,20,1,23],[24,23,21,33],[56,76,24,7])
sample_matrix

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [5]:
sample_matrix[1,2]

NameError: name 'sample_matrix' is not defined

In [6]:
sample_matrix[2,:]

NameError: name 'sample_matrix' is not defined

In [7]:
sample_matrix[2]

NameError: name 'sample_matrix' is not defined

In [8]:
sample_matrix[:,(3,2)]

NameError: name 'sample_matrix' is not defined

# 2-d Array

In [9]:
sample_matrix=np.array([50,20,1,23],[24,23,21,33],[56,76,24,7])
sample_matrix

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [12]:
sample_matrix[2,:]

NameError: name 'sample_matrix' is not defined

In [11]:
sample_matrix

NameError: name 'sample_martix' is not defined

In [13]:
sample_matrix[:,(3,2)]

NameError: name 'sample_matrix' is not defined

Two dimensional Array

In [ ]:
import numpy as np

In [14]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [15]:
sample_matrix[2,1]

76

In [16]:
sample_matrix[:,(2,3)]

array([[ 1, 23],
       [21, 33],
       [24,  7]])

In [17]:
sample_matrix[(3,2),:]

IndexError: index 3 is out of bounds for axis 0 with size 3

### Selection Techniques

In [20]:
sample_array=np.arange(1,20)

In [21]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [22]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [23]:
np.exp(sample_array) # exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [24]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [25]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [26]:
np.max(sample_array)

19

In [27]:
np.min(sample_array)

1

In [28]:
np.argmax(sample_array)

18

In [29]:
np.argmin(sample_array)

0

In [30]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [31]:
np.std(sample_array)

5.477225575051661

In [32]:
np.var(sample_array)

30.0

In [33]:
np.mean(sample_array)

10.0

In [35]:
array=np.random.randn(3,4)
array

array([[ 0.81932852,  0.42468854, -0.0632094 , -1.06653511],
       [ 2.10703795,  0.66150731, -0.01004105, -0.69889626],
       [-0.96128154, -2.07773366,  0.12401394,  0.24496852]])

In [36]:
np.round(array,decimals=2)

array([[ 0.82,  0.42, -0.06, -1.07],
       [ 2.11,  0.66, -0.01, -0.7 ],
       [-0.96, -2.08,  0.12,  0.24]])

In [37]:
sports=np.array(['golf','cricket','fball',])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

In [ ]:
### Panda

In [48]:
import pandas as pd
import numpy as np

### Pandas Dataframe and Indexing

In [40]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [41]:
sports1['football']

2

In [42]:
sports2=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports2

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [43]:
sports1+sports2

cricket       2
football      4
basketball    6
golf          8
dtype: int64

In [44]:
sports1['cricket']

1

In [56]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score 4 Score 5'.split())
df=pd.DataFrame

ValueError: Shape of passed values is (8, 5), indices imply (8, 7)

In [57]:
df["score1"]

NameError: name 'df' is not defined

In [58]:
df1[["Score1","Score2"]]

NameError: name 'df1' is not defined

In [59]:
df1['Score6']=df['Score1']+df['Score3']

NameError: name 'df' is not defined

In [60]:
df2={'ID'[:'101','103','107','176'],'Name':['John','mercy','akash'],:'profit':[20,45,50]}
df=pd.DataFrame(df2)
df

SyntaxError: invalid syntax (2567619454.py, line 1)

In [3]:
rand_array.max()

NameError: name 'rand_array' is not defined

In [2]:
a.T

NameError: name 'a' is not defined

In [5]:
import numpy as np
simple_list=[6,7,9]


In [6]:
rand_array.max()

NameError: name 'rand_array' is not defined

In [7]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
a=np.random.rand(2,3)
a

array([[0.81833008, 0.81329158, 0.58332559],
       [0.45689806, 0.10174609, 0.06240079]])

In [10]:
a=np.random.rand(3,4)
a

array([[0.57550274, 0.19329806, 0.57121383, 0.76461437],
       [0.3013517 , 0.46234127, 0.30179339, 0.89564608],
       [0.01512808, 0.24399952, 0.58267522, 0.54564179]])

In [11]:
a=np.random.rand(6,7)
a

array([[0.26665792, 0.77031263, 0.53254404, 0.91800004, 0.41908701,
        0.96281937, 0.0620817 ],
       [0.53074616, 0.20960434, 0.01837744, 0.7655745 , 0.2831365 ,
        0.67821121, 0.82441239],
       [0.46336494, 0.65604135, 0.15858525, 0.18226331, 0.13916559,
        0.78925931, 0.02571486],
       [0.90400216, 0.89774124, 0.56945312, 0.61990402, 0.99368304,
        0.40579909, 0.88760084],
       [0.38743594, 0.29637988, 0.49674341, 0.32474063, 0.44944053,
        0.12075106, 0.46067823],
       [0.733265  , 0.07808964, 0.8285574 , 0.17073944, 0.88408364,
        0.76037515, 0.70774416]])

In [12]:
a.T

array([[0.26665792, 0.53074616, 0.46336494, 0.90400216, 0.38743594,
        0.733265  ],
       [0.77031263, 0.20960434, 0.65604135, 0.89774124, 0.29637988,
        0.07808964],
       [0.53254404, 0.01837744, 0.15858525, 0.56945312, 0.49674341,
        0.8285574 ],
       [0.91800004, 0.7655745 , 0.18226331, 0.61990402, 0.32474063,
        0.17073944],
       [0.41908701, 0.2831365 , 0.13916559, 0.99368304, 0.44944053,
        0.88408364],
       [0.96281937, 0.67821121, 0.78925931, 0.40579909, 0.12075106,
        0.76037515],
       [0.0620817 , 0.82441239, 0.02571486, 0.88760084, 0.46067823,
        0.70774416]])

In [13]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
sample_array[0]

10

In [15]:
sample_array[2:5]

array([12, 13, 14])

In [16]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [17]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

samp

In [18]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [19]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [20]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two Dimensional Array

In [21]:
import numpy as np

In [22]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [23]:
sample_matrix[1,2]

21

In [24]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [25]:
sample_matrix[2]

array([56, 76, 24,  7])

In [26]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [28]:
sample_matrix[1,:]

array([24, 23, 21, 33])

### Selection Techniques

In [30]:
sample_array=np.arange(1,20)

In [31]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [32]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [33]:
np.exp(sample_array) # exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [34]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [35]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [36]:
np.std(sample_array)

5.477225575051661

In [37]:
np.var(sample_array)

30.0

In [38]:
np.mean(sample_array)

10.0

In [40]:
np.max(sample_array)

19

In [39]:
np.min(sample_array)

1

In [41]:
np.argmax(sample_array)

18

In [42]:
np.argmin(sample_array)

0

In [43]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [44]:
np.std(sample_array)

5.477225575051661

In [45]:
np.var(sample_array)

30.0

In [46]:
array=np.random.randn(3,4)
array

array([[-1.81116829, -1.67376976,  0.05977889, -0.23308818],
       [-0.54726677,  1.89204008, -0.70135687,  1.47177907],
       [-0.78458624,  1.3760865 , -0.97963646, -0.17783584]])

In [47]:
np.round(array,decimals=2)

array([[-1.81, -1.67,  0.06, -0.23],
       [-0.55,  1.89, -0.7 ,  1.47],
       [-0.78,  1.38, -0.98, -0.18]])

In [48]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

In [49]:
### Pandas

In [50]:
import pandas as pd 
import numpy as np

### Pandas dataframe and indexing

In [51]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [52]:
sports1['football']

2

In [53]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [54]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [55]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.296141  0.591262  0.043272  0.297858  0.183848
B  0.067356  0.279249  0.927151  0.775357  0.269818
C  0.204165  0.250154  0.716877  0.103146  0.417853
D  0.467394  0.935843  0.846573  0.483738  0.375149
E  0.495311  0.223833  0.922442  0.828059  0.020752
F  0.019762  0.805027  0.555143  0.581508  0.249675
G  0.309299  0.105370  0.690306  0.048545  0.397462
H  0.764812  0.831311  0.995362  0.091328  0.204185

In [57]:
df1["Score1"]

A    0.296141
B    0.067356
C    0.204165
D    0.467394
E    0.495311
F    0.019762
G    0.309299
H    0.764812
Name: Score1, dtype: float64

In [59]:
df1["Score2"]

A    0.591262
B    0.279249
C    0.250154
D    0.935843
E    0.223833
F    0.805027
G    0.105370
H    0.831311
Name: Score2, dtype: float64

In [60]:
df1["Score5"]

A    0.183848
B    0.269818
C    0.417853
D    0.375149
E    0.020752
F    0.249675
G    0.397462
H    0.204185
Name: Score5, dtype: float64

In [61]:
df1[["Score1","Score2"]]

Score1    Score2
A  0.296141  0.591262
B  0.067356  0.279249
C  0.204165  0.250154
D  0.467394  0.935843
E  0.495311  0.223833
F  0.019762  0.805027
G  0.309299  0.105370
H  0.764812  0.831311

In [63]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.296141  0.591262  0.043272  0.297858  0.183848  0.887404
B  0.067356  0.279249  0.927151  0.775357  0.269818  0.346605
C  0.204165  0.250154  0.716877  0.103146  0.417853  0.454319
D  0.467394  0.935843  0.846573  0.483738  0.375149  1.403237
E  0.495311  0.223833  0.922442  0.828059  0.020752  0.719144
F  0.019762  0.805027  0.555143  0.581508  0.249675  0.824789
G  0.309299  0.105370  0.690306  0.048545  0.397462  0.414669
H  0.764812  0.831311  0.995362  0.091328  0.204185  1.596123

In [64]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[10,25,22,78,124]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      10
1  102  Mercy      25
2  103  Akash      22
3  107  Kavin      78
4  176  Lally     124

In [65]:
df["ID"]

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [66]:
df["Name"]

0     John
1    Mercy
2    Akash
3    Kavin
4    Lally
Name: Name, dtype: object

In [67]:
df["Profit"]

0     10
1     25
2     22
3     78
4    124
Name: Profit, dtype: int64

In [68]:
df[["ID","Name"]]

ID   Name
0  101   John
1  102  Mercy
2  103  Akash
3  107  Kavin
4  176  Lally

In [69]:
df[["ID","Name","Profit"]]

ID   Name  Profit
0  101   John      10
1  102  Mercy      25
2  103  Akash      22
3  107  Kavin      78
4  176  Lally     124

In [70]:
df=df.drop("ID",axis=1)
df

Name  Profit
0   John      10
1  Mercy      25
2  Akash      22
3  Kavin      78
4  Lally     124

In [71]:
df

Name  Profit
0   John      10
1  Mercy      25
2  Akash      22
3  Kavin      78
4  Lally     124

In [72]:
df.drop(3)

Name  Profit
0   John      10
1  Mercy      25
2  Akash      22
4  Lally     124